export interface AnalysisResult {
    video: string;
    segments: Array<{
        timestamp: string;
        raw_timestamp: string;
        face_confidence_score: number;
        face_verdict: "TRUTH" | "LIE";
        arms_confidence_score: number;
        arms_verdict: "TRUTH" | "LIE";
        average_confidence_score_segment: number;
        verdict: string;
        parts_indicate: "arms" | "face";
        average_based_verdict: "TRUTH" | "LIE";
        face_image_b64: string;
    }>;
    summary: {
        average_confidence_score: number;
        final_verdict: string;
        total_segments_analyzed: number;
    };
}

// timewarp points are generated by the backend (or mocked) and attached to a video
export interface TimeWarpPoint {
    id: string;
    timestamp: number; // in seconds
    confidence: number; // 0-1
    label: string;
    partsIndicate?: "arms" | "face";
    thumbnail?: string;
}

export interface VideoItem {
    id: string;
    userId?: string;
    originalFilename: string;
    durationSeconds?: number;
    fileSize: number;
    uploadedAt: string;
    isAnonymous: boolean;
    isClaimed: boolean;
    analysisResult?: AnalysisResult;
    videoPath?: string;
    // optional timewarp data
    timeWarpPoints?: TimeWarpPoint[];
}


export const mockVideos: VideoItem[] = [
    {
        id: "1",
        userId: "user123",
        originalFilename: "Test",
        durationSeconds: 120,
        fileSize: 15728640,
        uploadedAt: "2024-02-22T10:30:00Z",
        isAnonymous: false,
        isClaimed: true,
        videoPath: "/videos/Test.mp4",
        analysisResult: {
            video: "Test.mp4",
            segments: [
                {
                    timestamp: "00:00 - 00:03",
                    raw_timestamp: "0.00-3.00",
                    face_confidence_score: 0.8123,
                    face_verdict: "LIE",
                    arms_confidence_score: 0.9372,
                    arms_verdict: "LIE",
                    average_confidence_score_segment: 0.8748,
                    verdict: "LIE",
                    parts_indicate: "arms",
                    average_based_verdict: "LIE",
                    face_image_b64: ""
                },
                {
                    timestamp: "00:03 - 00:06",
                    raw_timestamp: "3.00-6.00",
                    face_confidence_score: 0.8895,
                    face_verdict: "LIE",
                    arms_confidence_score: 0.9325,
                    arms_verdict: "LIE",
                    average_confidence_score_segment: 0.911,
                    verdict: "LIE",
                    parts_indicate: "arms",
                    average_based_verdict: "LIE",
                    face_image_b64: ""
                }
            ],
            summary: {
                average_confidence_score: 0.9349,
                final_verdict: "LIE",
                total_segments_analyzed: 2
            }
        },
        timeWarpPoints: [
            { id: "point-1", timestamp: 5, confidence: 0.85, label: "สงสัย" },
            { id: "point-2", timestamp: 15, confidence: 0.72, label: "เครียด" },
            { id: "point-3", timestamp: 28, confidence: 0.91, label: "โกหก" },
            { id: "point-4", timestamp: 42, confidence: 0.65, label: "ปกติ" }
        ]
    },
    {
        id: "2",
        userId: "user123",
        originalFilename: "Momo",
        durationSeconds: 120,
        fileSize: 15728640,
        uploadedAt: "2024-02-22T10:30:00Z",
        isAnonymous: false,
        isClaimed: true,
        videoPath: "/videos/Test.mp4",
        analysisResult: {
            video: "Momo.mp4",
            segments: [
                {
                    timestamp: "00:00 - 00:03",
                    raw_timestamp: "0.00-3.00",
                    face_confidence_score: 0.4567,
                    face_verdict: "TRUTH",
                    arms_confidence_score: 0.512,
                    arms_verdict: "TRUTH",
                    average_confidence_score_segment: 0.4844,
                    verdict: "TRUTH",
                    parts_indicate: "arms",
                    average_based_verdict: "TRUTH",
                    face_image_b64: ""
                },
                {
                    timestamp: "00:03 - 00:06",
                    raw_timestamp: "3.00-6.00",
                    face_confidence_score: 0.7234,
                    face_verdict: "LIE",
                    arms_confidence_score: 0.612,
                    arms_verdict: "LIE",
                    average_confidence_score_segment: 0.6677,
                    verdict: "LIE",
                    parts_indicate: "face",
                    average_based_verdict: "LIE",
                    face_image_b64: ""
                }
            ],
            summary: {
                average_confidence_score: 0.5901,
                final_verdict: "TRUTH",
                total_segments_analyzed: 2
            }
        },
        timeWarpPoints: [
            { id: "point-1", timestamp: 5, confidence: 0.85, label: "สงสัย" },
            { id: "point-2", timestamp: 15, confidence: 0.72, label: "เครียด" },
            { id: "point-3", timestamp: 28, confidence: 0.91, label: "โกหก" },
            { id: "point-4", timestamp: 42, confidence: 0.65, label: "ปกติ" }
        ]
    }
    
];

// Helper function to get video by ID
export const getMockVideoById = (id: string): VideoItem | undefined => {
    return mockVideos.find(video => video.id === id);
};