export interface AnalysisResult {
    isLieDetected: boolean;
    confidenceScore: number;
    status: string;
    analyzedAt?: string;
}

// timewarp points are generated by the backend (or mocked) and attached to a video
export interface TimeWarpPoint {
    id: string;
    timestamp: number; // in seconds
    confidence: number; // 0-1
    label: string;
    thumbnail?: string;
}

export interface VideoItem {
    id: string;
    userId?: string;
    originalFilename: string;
    durationSeconds?: number;
    fileSize: number;
    uploadedAt: string;
    isAnonymous: boolean;
    isClaimed: boolean;
    analysisResult?: AnalysisResult;
    videoPath?: string;
    // optional timewarp data
    timeWarpPoints?: TimeWarpPoint[];
}


export const mockVideos: VideoItem[] = [
    {
        id: "1",
        userId: "user123",
        originalFilename: "Test",
        durationSeconds: 120,
        fileSize: 15728640,
        uploadedAt: "2024-02-22T10:30:00Z",
        isAnonymous: false,
        isClaimed: true,
        videoPath: "/videos/Test.mp4",
        analysisResult: {
            isLieDetected: true,
            confidenceScore: 0.85,
            status: "completed",
            analyzedAt: "2024-02-22T10:45:00Z"
        },
        timeWarpPoints: [
            { id: "point-1", timestamp: 5, confidence: 0.85, label: "สงสัย" },
            { id: "point-2", timestamp: 15, confidence: 0.72, label: "เครียด" },
            { id: "point-3", timestamp: 28, confidence: 0.91, label: "โกหก" },
            { id: "point-4", timestamp: 42, confidence: 0.65, label: "ปกติ" }
        ]
    },
    {
        id: "2",
        userId: "user123",
        originalFilename: "Momo",
        durationSeconds: 120,
        fileSize: 15728640,
        uploadedAt: "2024-02-22T10:30:00Z",
        isAnonymous: false,
        isClaimed: true,
        videoPath: "/videos/Test.mp4",
        analysisResult: {
            isLieDetected: true,
            confidenceScore: 0.85,
            status: "completed",
            analyzedAt: "2024-02-22T10:45:00Z"
        },
        timeWarpPoints: [
            { id: "point-1", timestamp: 5, confidence: 0.85, label: "สงสัย" },
            { id: "point-2", timestamp: 15, confidence: 0.72, label: "เครียด" },
            { id: "point-3", timestamp: 28, confidence: 0.91, label: "โกหก" },
            { id: "point-4", timestamp: 42, confidence: 0.65, label: "ปกติ" }
        ]
    }
    
];

// Helper function to get video by ID
export const getMockVideoById = (id: string): VideoItem | undefined => {
    return mockVideos.find(video => video.id === id);
};